let allowed = [
  'T-shirt',
  'Jeans',
  'Shirt',
  'Sweater',
  'Trousers',
  'Cargo Pants',
  'Hoodie',
  'Jacket',
  'Dress Shirt',
  'Collar',
  'Suit',
  'Sweatpant',
  'Leggings',
  'Tights',
  'Khaki',
  'Polo Shirt',
  'Suit',
  'Shorts',
  'Blazer',
  'Pajamas',
  'Coat',
  'Leather Jacket',
  'Trench Coat',
  'Overcoat',
  'Crop Top',
  'Pajamas',
  'Coat',
  'Pencil Skirt',
  'Dress',
  'Gown',
  'Pantsuit',
  'Suit Trousers',
  'Cardigan',
  'Long-sleeved T-shirt',
  'Sweatshirt',
  'Jersey',
  'Plaid',
  'Parka',
  'Tuxedo',
  'Robe',
  'Gown',
  'Flip-flop',
  'Sandal',
  'Slipper',
  'Knee-high Boot',
  'Uniform',
  'Boot',
  'Dress shoe',
  'Dress Shoe',
  'Active Pants',
  'Rain Pants',
  'Yoga Pants',
  'High Heels',
  'Riding Boot',
  'Slingback',
  'Court Shoe',
  'Skort',
  'Cocktail Dress',
  'Cowboy Boot',
  'Sneakers',
  'Skate Shoe',
  'Walking Shoe',
  'Athletic Shoe',
  'Running Shoe',
  'Plimsoll Shoe',
  'Tennis Shoe',
  'Outdoor Shoe',
  'Rain Boot',
  'Durango Boot',
  'Snow Boot',
  'Wedge'
];

export default allowed;
